/** Códigos ISO → nombre en español (fallback: el propio código). */
export const CCNAME: Record<string, string> = {
  AR: 'Argentina',
  BR: 'Brasil',
  PE: 'Perú',
  GB: 'Reino Unido',
  CO: 'Colombia',
  MX: 'México',
  FR: 'Francia',
  CN: 'China',
  US: 'Estados Unidos',
  DE: 'Alemania',
  ES: 'España',
  AU: 'Australia',
  CL: 'Chile',
  CA: 'Canadá',
  IT: 'Italia',
  NL: 'Países Bajos',
  SE: 'Suecia',
  CH: 'Suiza',
  JP: 'Japón',
  IN: 'India',
  RU: 'Rusia',
  PT: 'Portugal',
  BE: 'Bélgica',
  AT: 'Austria',
  DK: 'Dinamarca',
  NO: 'Noruega',
  FI: 'Finlandia',
  PL: 'Polonia',
  IE: 'Irlanda',
  NZ: 'Nueva Zelanda',
  ZA: 'Sudáfrica',
  EC: 'Ecuador',
  UY: 'Uruguay',
  BO: 'Bolivia',
  PY: 'Paraguay',
  VE: 'Venezuela',
  CR: 'Costa Rica',
  CU: 'Cuba',
  KR: 'Corea del Sur',
  IL: 'Israel',
  TR: 'Turquía',
  GR: 'Grecia',
  CZ: 'Chequia',
  HU: 'Hungría',
  RO: 'Rumania',
};

export function ccName(cc: string): string {
  return CCNAME[cc] || cc;
}
